package projetobd;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class Modificar extends javax.swing.JDialog{

    Connection connection;
    String[] paises = null;
    private ImageIcon icone;
    
    /**
     * Creates new form Inserir
     */
    public Modificar(java.awt.Frame parent, boolean modal, Connection connection){
        super(parent, modal);
        this.connection = connection;
        this.icone = new ImageIcon(getClass().getResource("mascote.jpg"));
        this.setResizable(false);
        buscaPaises();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoID = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoData = new javax.swing.JFormattedTextField();
        campoPassaporte = new javax.swing.JFormattedTextField();
        campoSexo = new javax.swing.JComboBox();
        campoAltura = new javax.swing.JFormattedTextField();
        campoPeso = new javax.swing.JFormattedTextField();
        CampoPais = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        botaoModificar = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoErro = new javax.swing.JTextPane();
        botaoVoltar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botaoPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar atleta");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Digite o ID do atleta:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetobd/Tokyo-2020-menor.jpg"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID:");

        campoID.setText("000000");
        campoID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        try{
            MaskFormatter maskID = new MaskFormatter("######");
            maskID.setPlaceholderCharacter('_');
            maskID.install(campoID);
        }catch(ParseException ex){}
        campoID.setCaretPosition(0);
        campoID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoIDMouseClicked(evt);
            }
        });
        campoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Dada de nascimento:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nº do passaporte:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Sexo:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Altura:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Peso:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("País que representa:");

        campoNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoNome.setEnabled(false);
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });

        campoData.setText("19/02/92");
        campoData.setEnabled(false);
        campoData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        try{
            MaskFormatter maskID = new MaskFormatter("##/##/##");
            maskID.setPlaceholderCharacter('_');
            maskID.install(campoData);
        }catch(ParseException ex){}
        campoData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoDataMouseClicked(evt);
            }
        });
        campoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDataActionPerformed(evt);
            }
        });

        campoPassaporte.setText("AA000000");
        try{
            MaskFormatter maskID = new MaskFormatter("UU######");
            maskID.setPlaceholderCharacter('_');
            maskID.install(campoPassaporte);
        }catch(ParseException ex){}
        campoPassaporte.setEnabled(false);
        campoPassaporte.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoPassaporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPassaporteMouseClicked(evt);
            }
        });

        campoSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        campoSexo.setToolTipText("Selecione");
        campoSexo.setEnabled(false);

        campoAltura.setText("0,00");
        try{
            MaskFormatter maskID = new MaskFormatter("#,##");
            maskID.setPlaceholderCharacter('_');
            maskID.install(campoAltura);
        }catch(ParseException ex){}
        campoAltura.setEnabled(false);
        campoAltura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoAltura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoAlturaMouseClicked(evt);
            }
        });
        campoAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAlturaActionPerformed(evt);
            }
        });

        campoPeso.setText("000,000");
        try{
            MaskFormatter maskID = new MaskFormatter("###,###");
            maskID.setPlaceholderCharacter('_');
            maskID.install(campoPeso);
        }catch(ParseException ex){}
        campoPeso.setEnabled(false);
        campoPeso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoPeso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPesoMouseClicked(evt);
            }
        });

        CampoPais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CampoPais.setModel(new javax.swing.DefaultComboBoxModel(paises));
        CampoPais.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        botaoModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoModificar.setText("Modificar");
        botaoModificar.setEnabled(false);
        botaoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModificarActionPerformed(evt);
            }
        });

        botaoRemover.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoRemover.setText("Remover");
        botaoRemover.setEnabled(false);
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        campoErro.setBorder(null);
        campoErro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(campoErro);

        botaoVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Kg");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("metros");

        botaoPesquisar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(campoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(campoPassaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(CampoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(campoNome))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoPassaporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CampoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIDActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDataActionPerformed

    private void campoIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoIDMouseClicked
        campoID.setCaretPosition(0);
    }//GEN-LAST:event_campoIDMouseClicked

    private void campoDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoDataMouseClicked
        campoData.setCaretPosition(0);
    }//GEN-LAST:event_campoDataMouseClicked

    private void campoPassaporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPassaporteMouseClicked
        campoPassaporte.setCaretPosition(0);
    }//GEN-LAST:event_campoPassaporteMouseClicked

    private void campoAlturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoAlturaMouseClicked
        campoAltura.setCaretPosition(0);
    }//GEN-LAST:event_campoAlturaMouseClicked

    private void campoAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAlturaActionPerformed

    private void botaoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModificarActionPerformed
        String insert;
        insert = "UPDATE ATLETA SET NOME = '" + campoNome.getText() + "', DATANASCIMENTO = '" +
                campoData.getText() + "', NPASSAPORTE = '" + campoPassaporte.getText() 
                + "', SEXO = '";
        if(campoSexo.getSelectedIndex() == 0){
            insert += "M";
        }else{
            insert += "F";
        }
        insert += "', ALTURA = '" + campoAltura.getText() + "', PESO = '" + campoPeso.getText() 
                + "', PAIS = '" + (String) CampoPais.getSelectedItem() + "' WHERE ID_ = '" +
                campoID.getText() + "'";
        
        try{
            PreparedStatement pstmt = connection.prepareStatement(insert);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Dados atualizados", "Tóquio 2020", WIDTH, icone);
            pstmt.close();
            this.dispose();
        } catch (SQLException e) {
            campoErro.setText("Dados não foram atualizados. Erro:\n" + e.getMessage());
        }
        
    }//GEN-LAST:event_botaoModificarActionPerformed

    private void campoPesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPesoMouseClicked
        campoPeso.setCaretPosition(0);
    }//GEN-LAST:event_campoPesoMouseClicked

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        String delete;
        delete = "DELETE ATLETA WHERE ID_ = '" + campoID.getText() + "'";
        
        System.out.println(delete);
        
        try{
            PreparedStatement pstmt = connection.prepareStatement(delete);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Atleta excluído", "Tóquio 2020", WIDTH, icone);
            pstmt.close();
            this.dispose();
        } catch (SQLException e) {
            campoErro.setText("Atleta não foi exluído. Erro:\n" + e.getMessage());
        }
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        try{
            Statement stmt;
            ResultSet rs;
            stmt = connection.createStatement();
            rs = stmt.executeQuery("SELECT * FROM ATLETA WHERE ID_ = " + campoID.getText());
            
            rs.next();
            campoNome.setText(rs.getString("NOME"));
            campoNome.setEnabled(true);
            
            String data = rs.getString("DATANASCIMENTO");
            String dataCerta = Character.toString(data.charAt(8)) + Character.toString(data.charAt(9)) +
                    "/" + Character.toString(data.charAt(5)) + Character.toString(data.charAt(6)) +
                    "/" + Character.toString(data.charAt(2)) + Character.toString(data.charAt(3));
            campoData.setText(dataCerta);        
            campoData.setEnabled(true);
            
            campoPassaporte.setText(rs.getString("NPASSAPORTE"));
            campoPassaporte.setEnabled(true);
            
            if(rs.getString("SEXO").equals("M")){
                campoSexo.setSelectedIndex(0);
            }else{
                campoSexo.setSelectedIndex(1);
            }
            campoSexo.setEnabled(true);
            
            float altura = Float.valueOf(rs.getString("ALTURA"));
            DecimalFormat df = new DecimalFormat("0.00");
            campoAltura.setText(df.format(altura).replace('.', ','));
            campoAltura.setEnabled(true);
            
            float peso = Float.valueOf(rs.getString("PESO"));
            DecimalFormat df2 = new DecimalFormat("000.000");
            campoPeso.setText(df2.format(peso).replace('.', ','));
            campoPeso.setEnabled(true);
            
            CampoPais.setSelectedItem(rs.getString("PAIS"));
            CampoPais.setEnabled(true);
            
            campoID.setEnabled(false);
            botaoPesquisar.setText("Desfazer");
            
            campoErro.setText("");
            botaoModificar.setEnabled(true);
            botaoRemover.setEnabled(true);
            
            stmt.close();
            
        }catch(SQLException ex){
            campoErro.setText("Não existe atleta com esse ID.\nTente novamente.");
        }
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void buscaPaises(){
        try{
            Statement stmt;
            ResultSet rs;
            ArrayList paisesA = new ArrayList();
            stmt = connection.createStatement();
            rs = stmt.executeQuery("SELECT NOME FROM PAIS");
            while (rs.next()) {
                paisesA.add(rs.getString(1));
            }
            paises = (String[]) paisesA.toArray(new String[paisesA.size()]);
            
        }catch(SQLException ex){
            Logger.getLogger(Inserir.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CampoPais;
    private javax.swing.JButton botaoModificar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JFormattedTextField campoAltura;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JTextPane campoErro;
    private javax.swing.JFormattedTextField campoID;
    private javax.swing.JTextField campoNome;
    private javax.swing.JFormattedTextField campoPassaporte;
    private javax.swing.JFormattedTextField campoPeso;
    private javax.swing.JComboBox campoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
